export const MESSAGE = {
  edit: "Edited successfully.",
  editAndPub: "Edited and published successfully.",
  delete: "Deleted successfully.",
  confirm: "Confirmed successfully.",
  create: "Added successfully.",
  createAndPub: "Added and published successfully.",
  addAndInvite: "Added and invitation sent successfully.",
  deactivate: "Deactivated successfully.",
  activate: "Activated successfully.",
  reject: "Rejected successfully.",
  approve: "Approved successfully.",
  copy: "Duplicated successfully.",
  disabled: "Disabled successfully.",
  enabled: "Enabled successfully.",
  save: "Saved successfully.",
  sent: "Sent successfully.",
  invitationSent: "Invitation sent successfully.",
  import: "Imported successfully.",
  sentInvitation: "Invitation sent successfully.",
  joinCommunity: "Joined successfully, please login.",
  sendEmail: "Email sent successfully.",
  signUp: "Signed up successfully.",
  assign: "Assigned successfully.",
  apply: "Applied successfully.",
  publish: "Published successfully.",
  unpublish: "Unpublished successfully.",
  waitingForApproval: "Request sent successfully.",
  loginError: "Login failed.",
  passwordNotMatch: "Password and confirm password do not match.",
  resetPassword: "Password reset successfully.",
  networkError: "Network Error.",
  getListError: "Failed to get the list.",
  editError: "Failed to edit the item.",
  createError: "Failed to create the item.",
  deleteError: "Failed to delete the item.",
  locationSelectError_map: "Please select the location on the map.",
  fillLimit_5M: "Please upload pictures smaller than 5M.",

  approve_failed: "Approval failed.",
  editinvitation: "Edited and invitation sent successfully.",
  workerExists: "This user is already in the Employees list.",

  deleteCommpany: "Are you sure you want to delete this company?",
  // deactivateCommpany: "Are you sure you want to deactivate this company?",
  deactivateCommpany:
    "Once it is deactivated, all the communities associated to it are not able to log in any more. Are you sure to proceed?",
  activateCommpany: "Are you sure you want to activate this company?",
  deactivateCommunity:
    "Once it is deactivated, all the users associated to it are not able to log in any more. Are you sure to proceed?",
  activateCommunity: "Are you sure you want to activate this community?",
  deleteCommunity: "Are you sure you want to delete this community?",
};
