import { NeedHelpShiftStatusVo } from "@/app/(system)/(service)/shiftsNeedHelp/types";
export type shiftSwapResVO = {
  id: string | null;
  shiftId: string | null;
  type: number;
  status: NeedHelpShiftStatusVo;
  reviewComment: string | null;
  reviewAt: string | null;
  reviewBy: string | null;
  createdAt: string | null;
  createdBy: string | null;
  updatedAt: string | null;
  updatedBy: string | null;
  reason: string | null;
  shiftInfo: {
    id: string | null;
    scheduleId: string | null;
    communityId: string | null;
    departmentId: string | null;
    departmentName: string | null;
    locationRefVOs: {
      id: string | null;
      locationName: string | null;
      locationId: string | null;
    }[];
    workerRoleId: string | null;
    workerRoleName: string | null;
    workerRoleColor: string | null;
    userId: string | null;
    userName: string | null;
    dayOfWeek: number;
    startTimeLocal: string | null;
    endTimeLocal: string | null;
    shiftStartTime: string | null;
    startTimeUTC: string;
    endTimeUTC: string;
    shiftEndTime: string | null;
    shiftDate: string | null;
    durationMins: number;
    paidMins: string | null;
    status: string | null;
    note: string | null;
    breakRequiredMins: string | null;
    checkinTime: string | null;
    checkoutTime: string | null;
    parentId: string | null;
    isPartialShift: string | null;
    isPublished: boolean;
    tags: number[] | null;
  };
  shiftUserProfile: {
    id: string | null;
    userId: string | null;
    firstName: string | null;
    lastName: string | null;
    middleName: string | null;
    portraitFileId: string | null;
    email: string | null;
    phone: string | null;
    nationalPhone: string | null;
    fullName: string | null;
  };
  swapRequestList: {
    id: string | null;
    shiftId: string | null;
    targetShiftId: string | null;
    userId: string | null;
    targetUserId: string | null;
    status: string | null;
    shiftReviewId: string | null;
    tags: number[] | null;
    targetTags: string | null;
    targetUserFirstName: string | null;
    targetUserLastName: string | null;
    targetUserPhone: string | null;

    targetShift: {
      id: string | null;
      scheduleId: string | null;
      communityId: string | null;
      departmentId: string | null;
      departmentName: string | null;
      locationRefVOs: {
        id: string | null;
        locationName: string | null;
        locationId: string | null;
      }[];
      workerRoleId: string | null;
      workerRoleName: string | null;
      workerRoleColor: string | null;
      userPhone: string | null;
      userId: string | null;
      userName: string | null;
      dayOfWeek: string | null;
      startTimeLocal: string | null;
      startTimeUTC: string | null;
      endTimeLocal: string | null;
      endTimeUTC: string | null;
      shiftStartTime: string | null;
      shiftEndTime: string | null;
      shiftDate: string | null;
      durationMins: string | null;
      paidMins: string | null;
      status: string | null;
      note: string | null;
      breakRequiredMins: string | null;
      checkinTime: string | null;
      checkoutTime: string | null;
      parentId: string | null;
      isPartialShift: string | null;
      isPublished: string | null;
      tags: number[] | null;
    };
    sourceShift: string | null;
  }[];
};
